import os

OPEN_WEATHER_TOKEN = os.environ['OPEN_WEATHER_TOKEN']
WEATHER_BIT_TOKEN = os.environ['WEATHER_BIT_TOKEN']
ACCU_WEATHER_TOKEN = os.environ['ACCU_WEATHER_TOKEN']
GEOCODE_TOKEN = os.environ['GEOCODE_TOKEN']
